// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0I0mNsqKxl4k8fB5qVjfLVHYQX16nKk',
    appId: '1:1034232946967:web:f6d2f6ece68f8a46999752',
    messagingSenderId: '1034232946967',
    projectId: 'baltic-deals-app',
    authDomain: 'baltic-deals-app.firebaseapp.com',
    storageBucket: 'baltic-deals-app.firebasestorage.app',
    measurementId: 'G-G6PWB0XW97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOoMORGxV6NcHwVJZ3TKx7-rbK8ZKBVZc',
    appId: '1:1034232946967:android:97f6b6423ee4c794999752',
    messagingSenderId: '1034232946967',
    projectId: 'baltic-deals-app',
    storageBucket: 'baltic-deals-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQJ-3X-lzsd1701Dmq74OwW3gXJYbz2o',
    appId: '1:1034232946967:ios:a8602d59df1d5f86999752',
    messagingSenderId: '1034232946967',
    projectId: 'baltic-deals-app',
    storageBucket: 'baltic-deals-app.firebasestorage.app',
    iosBundleId: 'com.example.balticDealsApp',
  );
}
